<?php
@define('MIMBO_INSTR','<b>Note:</b> The template supports - only on the start page - a single accompanying image per entry. For this feature to actually work, the s9y event plugin <i>Extended properties for entries</i> has to be installed. In the configuration of this plugin, a field called MimboImage (mind the captalization!) has to be set up under <i>Custom Fields</i>. When posting a new entry to the blog, an image from the media database can now be assigned to it under <i>Advanced Options</i>. The recommended width for these images depends on the Mimbo category (see below) the entry is assigned to.<br /><br /><b>Mimbo categories:</b> The Mimbo template displays entries in three areas on the start page. Use the following dropdown boxes to assign s9y categories to these Mimbo categories. The lead category will display its most recent entry (recommended width for the accompanying image: 270 pixels max). The features category will display links to its latest three entries (recommenden width for the accompanying image: 255 pixels max). Finally, select three news categories. Each of them will display its most recent entry as a shortened teaser (recommended width for the accompanying image: 60 pixels max).<br /><br />');
@define('MIMBO_CAT_LEAD','Select lead category');
@define('MIMBO_CAT_FEAT','Select features category');
@define('MIMBO_CAT_X1','Select first news category');
@define('MIMBO_CAT_X2','Select second news category');
@define('MIMBO_CAT_X3','Select third news category');
@define('MIMBO_CAT_X4','Select fourth news category');
@define('NAVLINK_AMOUNT', 'Enter number of links in the navbar (needs reload of the Manage Styles page; link to the index page of the blog will be added automatically)');
@define('NAV_LINK_TEXT', 'Enter the navbar link text');
@define('NAV_LINK_URL', 'Enter the full URL of your link');

@define('HORZ_NAV_LINK_TITLE', 'Horiz. Navigation Link');
@define('DROPDOWN_AMOUNT', 'Number of dropdown menue links (Use the link "Manage Styles" to reload and to see the changes)');
@define('DROPDOWN_TEXT', '  Text dropdown menue link ');
@define('DROPDOWN_URL', '  URL dropdown menue linkt ');
@define('SBMENUES_AMOUNT', 'Number of Menues in sidebar (Use the link "Manage Styles" to reload and to see the changes)');
@define('SBHEADER_TEXT', 'menue header');
@define('SBHEADER_URL', 'URL of  menue header ');
@define('SIDEBARMENUE_AMOUNT', 'Number of menue links (Use the link "Manage Styles" to reload and to see the changes)');
@define('SIDEBARMENUE_TEXT', 'Text of menue link');
@define('SIDEBARMENUE_URL', 'URL of menue link');
@define('SBMENUE_TITLE', 'Menue ');
@define('SB_TARGET', 'How to open the link?');

@define('MIMBO_TAB_X1','Choose 1. Tab Cat ');
@define('MIMBO_TAB_X2','Choose 2. Tab Cat ');
@define('MIMBO_TAB_X3','Choose 3. Tab Cat ');
@define('MIMBO_TAB_X4','Choose 4. Tab Cat ');
@define('INFO_TAB','<b><p style="color:#FFFFFF; background-color: gray"> TAB WINDOW </p></b>');
@define('ENABLECAT_TABA','activate the tab-window?');
@define('ENABLECAT_HMENUE','Activate the horizontal menue?');
@define('ENABLECAT_LEAD','Activate lead category?');
@define('MAGAZINE_MODE','Activate magazine mode?');
@define('INFO_LEAD','<b><p style="color:#000000; background-color:yellow"> Leading WINDOW </p></b>');
@define('INFO_NEWS','<b><p style="color:#ffffff; background-color:darkmagenta"> News  </p></b>');
@define('INFO_FEAT','<b><p style="color:#ffffff; background-color:darkgreen"> Featured  WINDOW </p></b>');
@define('INFO_TABKLOTZAMOUNT','<b><p style="color:#ffffff; background-color:orange"> TAB Klotz WINDOW (you will find TAB entries belower after reload)</p></b>');
@define('INFO_SBARMENUESAMOUNT','<b><p style="color:#ffffff; background-color:red"> Additional menues (you will find menue entries belower after reload)(</p></b>');
@define('INFO_HMENUE','<b><p style="color:#ffffff; background-color:#0066FF"> Horizontal-Menue (you will find menue entries belower after reload)</p></b>');
@define('TABKLOTZ_AMOUNT','Number of tab-klotz windows ');
@define('CATBANNER_AMOUNT','Number of category-banner ');
@define('KLOTZWIN_NAME','  distinct name  ');
@define('ENABLE_TABX1','  Activate 1. tab category? ');
@define('ENABLE_TABX2','  Activate 2. tab category? ');
@define('ENABLE_TABX3','  Activate 3. tab category? ');
@define('ENABLE_STICKY',' Activate 4. tab categorie with the sticky entries? ');
@define('SICKY_HEADER','  Heading of 4. tab  (sticky entries) : ');
@define('INFO_CBA_AMOUNT','<b><p style="color:#ffffff; background-color:olive">   category-banner (find the changes after reload the page)</p></b>');
@define('SB_POSITION',' Position: ');
@define('ENABLE_FOOTER',' Activate the footer? ');
@define('MIMBO_CAT_ROL',' Choose categoty for roll-meune: ');
@define('LEFTSIDEBAR_POS',' Position of the left sidebar: ');
@define('TABKLOTZ_POSITION',' TAB-position: ');
@define('TABKLOTZ_HEIGHT',' TAB high in px: ');
@define('TABTEXT',' TAB-text (html): ');
@define('TABKLOTZ_HEIGHT',' TAB-heading: ');
@define('CAT_IMAGE_TITLE',' Category image ');
@define('CATBANNER_POSITION',' Position of category images: ');
@define('IMAGE_TO_CAT',' Choose category: ');
@define('INFO_ROL','<b><p style="color:#000000; background-color:#FFCCFF"> Rollmenue window </p></b>');
@define('ENABLECAT_ROL',' Activate roll-menue? ');
@define('CATROL_HEADER',' Heading of roll-menue: ');
@define('ENABLE_TOPSIDEBAR',' Activate tab window  TOP-Sidebar? ');