<?php
@define('J_INSTR','<strong>zu installierende Plugins</strong>: <br>Damit das Menue korrekt funktioniert, müssen folgende Plugins installiert sein: <em><br>Archive </em>(Spalte versteckt) <br>- Anzahl der Einträge pro Kategorie anzeigen?&nbsp; Nein <br>- Versteckt den Archiv-Link, wenn es keine Einträge für einen Zeitraum gab:&nbsp; Nein<br><br>K<em>ategorien </em>(Spalte versteckt)<br>- XML-Button :none<br>- Besuchern erlauben, mehrere Kategorien gleichzeit darzustellen? Nein<br>-Smarty-Templating aktivieren?&nbsp; Ja<br /><br><em>Statischen Seiten&nbsp; </em>&nbsp;<br />Icons bzw. Klartext <b>: </b>Klartext<br>Grafiken für Baumstruktur aktivieren: Nein<b><br><br></b>Wenn auch <strong>statische Seiten</strong> in der Menuezeile angezeigt werden sollen, dann ändere die Zeile 252 der Datei&nbsp; <em><strong>/plugins/serendipity_event_staticpage/serendipity_plugin_staticpage.php </strong></em>von <br>alt: <strong><em>? </em></strong><strong><em>sprintf(&nbsp; &quot;&lt;a href=\&quot;%s\&quot; title=\&quot;%s\&quot; style=\&quot;padding-left: %dpx;\&quot;&gt;%s&lt;/a&gt;&lt;br /&gt;\n&quot;, </em></strong><br>neu: <strong><em>? sprintf( &quot;&lt;li&gt; &lt;a href=\&quot;%s\&quot; &gt;%s&lt;/a&gt;&lt;/li&gt;\n&quot;,</em></strong><b><br><br><br>Hinweis:</b>Damit im Template die Anzeige der Tags korrekt funktioniert, muss in der Konfiguration des Event-Plugins <em>Freie Artikel-Tags</em> die Option <em>Zeige die Tags in der Fußzeile an?</em> auf <em>Smarty</em> gesetzt werden<br><br>');
@define('J_MENUTITLE', 'Titel für das Menü in der Seitenleiste');
@define('J_MENUTEXT', 'Seiten');
@define('J_SEARCHFIELD','Suchbegriffe eingeben');
@define('J_SEARCHINFO','Archive der Seite durchsuchen');
@define('J_SUBMITTEXT','Suche');
@define('J_SUBMITALT','Klicken, um Archive zu durchsuchen');
@define('J_WITH', 'Mit');
@define('J_WITHOUT','Ohne');
@define('J_POSTED', 'Abgelegt');
@define('J_COMMTS', 'Kommentaren');
@define('J_TO', 'zu');
@define('NAVLINK_AMOUNT', 'Anzahl der Links in der Navigationsleiste (Styles verwalten-Seite muss danach neu geladen werden)');
@define('NAV_LINK_TEXT', 'Text des Navigationsleisten-Links');
@define('NAV_LINK_URL', 'URL des Navigationsleisten-Links');
@define('WPP_DDD','Werbungsblock');
@define('ADDVTEXT','your google code');
@define('DRNAV_LINK_TEXT', 'Text des Drop Down-Links');
@define('DRNAV_LINK_URL', 'URL des Drop Down-Links');
@define('DROP_D1', 'Anzahl der Links im User Drop Down Menuepunkt');
@define('USER_DROP', 'Anzeige User Drop Down Menuepunkt');
@define('DROP_HEADER', 'Name des User Drop Down-Links');
@define('ENABLE_KAT','Anzeige der Kategorien im Menue');
@define('ENABLE_ARCH','Anzeige der Archive im Menue');
@define('ENABLE_STAT','Anzeige der statischen Seiten im Menue');
@define('ENABLE_USER','Anzeige des User Dop Down Menue Punkts. (Einträge und Anzahl weiter unten)');
@define('ENABLE_LOG','Anzeige des Login und Verwaltungsmenues im Menue');
@define('STAT_HEADER','Beschriftung Drop Down Menuepunkt der statischen Seiten');
@define('MY_ADDTHIS_ACCOUNT', 'Dein AddThis.com Name. Hast Du keinen mach Dir dort einen');
@define('ENABLE_AD','Anzeige des ADDTHIS Buttons?');
@define('SHOW_PAGIBOTTOM','Zusaetzliche Seitennummerierung im Fuss anzeigen');
@define('SHOW_PAGITOP','Zusaetzliche Seitennummerierung im Content-Kopf anzeigen');