<?php
@define('J_INSTR','<strong>Plugins to install</strong>: <br>to make the menue bar working correct, you have to install the plugin : <em><br><br>Archive </em>(hidden sidebar) <br>- Show number of entries per category?&nbsp; No <br>- Hide archives link when no entries were made:&nbsp; No<br><br><em>Categories </em>(hidden sidebar)<br>- XML-Button :none<br>- Allow visitors to display multiple categories at once? No<br>- Enable Smarty-Templates? &nbsp; Yes<br /><br><em>Staticpage&nbsp; </em>&nbsp;<br />Icons or plain Text <b>: </b>Plain Text<br>Use plugin image directory : N<b>o<br><br></b>If you want to use <strong>staticpages</strong> in the menuebar you have to change Line 252 of the file&nbsp; <em><strong>/plugins/serendipity_event_staticpage/serendipity_plugin_staticpage.php&nbsp;&nbsp; </strong></em>from <br>old: <strong><em>? sprintf(&nbsp; &quot;&lt;a href=\&quot;%s\&quot; title=\&quot;%s\&quot; style=\&quot;padding-left: %dpx;\&quot;&gt;%s&lt;/a&gt;&lt;br /&gt;\n&quot;, </em></strong><br><br>to <br>new: <strong><em>? sprintf( &quot;&lt;li&gt; &lt;a href=\&quot;%s\&quot; &gt;%s&lt;/a&gt;&lt;/li&gt;\n&quot;,</em></strong><b><br><br><br>Note:</b>For the tags to display correctly in the template, you need to go to the configuration of the event plugins Tagging of entries and set the option Show tags in footer to <strong>Smarty</strong>.<br><b><br>');
@define('J_MENUTITLE', 'Title for the menu in the sidebar');
@define('J_MENUTEXT', 'Pages');
@define('J_SEARCHFIELD','Enter keyword to search');
@define('J_SEARCHINFO','search site archives');
@define('J_SUBMITTEXT','search');
@define('J_SUBMITALT','Click to search archives');
@define('J_WITH', 'with');
@define('J_WITHOUT','without');
@define('J_POSTED', 'Posted');
@define('J_COMMTS', 'Comments');
@define('J_TO', 'to');
@define('NAVLINK_AMOUNT', 'Enter number of links in the navbar (needs reload of the Manage Styles page)');
@define('NAV_LINK_TEXT', 'Enter the navbar link text');
@define('NAV_LINK_URL', 'Enter the full URL of your link');
@define('WPP_DDD','Addvertising');
@define('ADDVTEXT','your google code');
@define('NAV_LINK_TEXT', 'Enter the drop-down-link text');
@define('NAV_LINK_URL', 'Enter the full URL of drop-down-link');
@define('DROP_D1', 'Enter number of links for the  User Drop Down Menue');
@define('USER_DROP', 'Enable User Drop Down Menue ');
@define('DROP_HEADER', 'Name of user drop down-Link');
@define('ENABLE_KAT','Show Categories in menue');
@define('ENABLE_ARCH','Show archive in menue');
@define('ENABLE_STAT','Show static pages in menue');
@define('ENABLE_USER','Show des User Dop Down Menue  (entries and numbers below of this page)');
@define('ENABLE_LOG','Show  login in menue');
@define('DRNAV_LINK_TEXT', 'Text Drop Down-Link');
@define('DRNAV_LINK_URL', 'URL  Drop Down-Link');
@define('STAT_HEADER','Headline drop down menue for static pages');
@define('ENABLE_AD','Enable addthis button?');
@define('MY_ADDTHIS_ACCOUNT','Your addthis accout. If you don´t have one goto addthis.com ');
@define('SHOW_PAGITOP','Show additional page numbers in top of content');
@define('SHOW_PAGIBOTTOM','Show additional page numbers in footer');