<?php
@define('J_INSTR','<b>zu installierende Plugins:</b> Damit das Menue korrekt funktioniert, müssen folgende Plugins installiert sein: <em><br>Archive </em>(Spalte versteckt) <br>- <strong>Anzahl der Einträge pro Kategorie anzeigen?&nbsp; Nein <br>- Versteckt den Archiv-Link, wenn es keine Einträge für einen Zeitraum gab:&nbsp; Nein<br><br></strong>K<em><strong>ategorien </strong></em><strong><br>- XML-Button</strong> :none<br><strong>- Besuchern erlauben, mehrere Kategorien gleichzeit darzustellen? Nein</strong><br>-<strong>Smarty-Templating aktivieren?</strong>&nbsp; Ja<br /><br /><b>Hinweis:</b>Damit im Template die Anzeige der Tags korrekt funktioniert, muss in der Konfiguration des Event-Plugins <em>Freie Artikel-Tags</em> die Option <em>Zeige die Tags in der Fußzeile an?</em> auf <em>Smarty</em> gesetzt werden');
@define('J_MENUTITLE', 'Titel für das Menü in der Seitenleiste');
@define('J_MENUTEXT', 'Seiten');
@define('J_SEARCHFIELD','Suchbegriffe eingeben');
@define('J_SEARCHINFO','Archive der Seite durchsuchen');
@define('J_SUBMITTEXT','Suche');
@define('J_SUBMITALT','Klicken, um Archive zu durchsuchen');
@define('J_WITH', 'Mit');
@define('J_WITHOUT','Ohne');
@define('J_POSTED', 'Abgelegt');
@define('J_COMMTS', 'Kommentaren');
@define('J_TO', 'zu');
@define('NAVLINK_AMOUNT', 'Anzahl der Links in der Navigationsleiste (Styles verwalten-Seite muss danach neu geladen werden)');
@define('NAV_LINK_TEXT', 'Text des Navigationsleisten-Links');
@define('NAV_LINK_URL', 'URL des Navigationsleisten-Links');
@define('WPP_DDD','Werbungsblock');
@define('ADDVTEXT','your google code');
@define('DRNAV_LINK_TEXT', 'Text des Drop Down-Links');
@define('DRNAV_LINK_URL', 'URL des Drop Down-Links');
@define('DROP_D1', 'Anzahl der Links im User Drop Down Menuepunkt');
@define('USER_DROP', 'Anzeige User Drop Down Menuepunkt');
@define('DROP_HEADER', 'Name des User Drop Down-Links');
@define('ENABLE_KAT','Anzeige der Kategorien im Menue');
@define('ENABLE_ARCH','Anzeige der Archive im Menue');
@define('ENABLE_STAT','Anzeige der statischen Seiten im Menue');
@define('ENABLE_USER','Anzeige des User Dop Down Menue Punkts. (Einträge und Anzahl weiter unten)');
@define('ENABLE_LOG','Anzeige des Login und Verwaltungsmenues im Menue');
@define('STAT_HEADER','Beschriftung Drop Down Menüpunkt der statischen Seiten');
@define('MY_ADDTHIS_ACCOUNT', 'Dein AddThis.com Name. Hast Du keinen mach Dir dort einen');
@define('ENABLE_AD','Anzeige des ADDTHIS Buttons?');
@define('SHOW_PAGITOP','Zusätzliche Seitennummerierung im Fuss anzeigen');
@define('SHOW_PAGIBOTTOM','Zusätzliche Seitennummerierung im Content-Kopf anzeigen');