<?php
@define('THEME_COLORSET', 'Select colorset option');
@define('THEME_YELLOW', 'Yellow');
@define('THEME_AQUA', 'Aqua');
@define('NAVLINK1_TEXT_TITLE', 'Navlink #1 Text'); 
@define('NAVLINK1_TEXT_DESC', 'Enter the first navigation text');
@define('NAVLINK1_TEXT_DEFAULT', 'About');
@define('NAVLINK1_URL_TITLE', 'Navlink #1 URL');
@define('NAVLINK1_URL_DESC', 'Enter the first navigation URL eg \'http://www.somesite.url\'');
@define('NAVLINK1_ALT_TITLE', 'Navlink #1 Description');
@define('NAVLINK1_ALT_DESC', 'Enter the first navigation description (20 characters)');
@define('NAVLINK1_ALT_DEFAULT', 'All About Me');
@define('NAVLINK2_TEXT_TITLE', 'Navlink #2 Text'); 
@define('NAVLINK2_TEXT_DESC', 'Enter the second navigation text');
@define('NAVLINK2_TEXT_DEFAULT', 'Photos');
@define('NAVLINK2_URL_TITLE', 'Navlink #2 URL');
@define('NAVLINK2_URL_DESC', 'Enter the second navigation URL eg \'http://www.somesite.url\'');
@define('NAVLINK2_ALT_TITLE', 'Navlink #2 Description');
@define('NAVLINK2_ALT_DESC', 'Enter the second navigation description (20 characters)');
@define('NAVLINK2_ALT_DEFAULT', 'Piccies');
@define('NAVLINK3_TEXT_TITLE', 'Navlink #3 Text'); 
@define('NAVLINK3_TEXT_DESC', 'Enter the third navigation text');
@define('NAVLINK3_TEXT_DEFAULT', 'Projects');
@define('NAVLINK3_URL_TITLE', 'Navlink #3 URL');
@define('NAVLINK3_URL_DESC', 'Enter the third navigation URL eg \'http://www.somesite.url\'');
@define('NAVLINK3_ALT_TITLE', 'Navlink #3 Description');
@define('NAVLINK3_ALT_DESC', 'Enter the third navigation description (20 characters)');
@define('NAVLINK3_ALT_DEFAULT', 'What I Do');
@define('NAVLINK4_TEXT_TITLE', 'Navlink #4 Text'); 
@define('NAVLINK4_TEXT_DESC', 'Enter the fourth navigation text');
@define('NAVLINK4_TEXT_DEFAULT', 'Contact');
@define('NAVLINK4_URL_TITLE', 'Navlink #4 URL');
@define('NAVLINK4_URL_DESC', 'Enter the fourth navigation URL eg \'http://www.somesite.url\'');
@define('NAVLINK4_ALT_TITLE', 'Navlink #4 Description');
@define('NAVLINK4_ALT_DESC', 'Enter the fourth navigation description (20 characters)');
@define('NAVLINK4_ALT_DEFAULT', 'Send a msg');